name: TF project path
author: Pavel Snagovsky
description: Fetches files chnaged for a PR and outputs a directory, intended for Terraform monorepos

inputs:
  depth:
    default: "1"
    description: "Terraform project directory depth"
    required: false
  include:
    description: "Project names to include"
    required: false
  exclude:
    description: "Paths to exclude"
    required: false
    default: ".github,tmp"
  token:
    description: "Github runner token."
    required: true
    default: ${{ github.token }}
  pr_number:
    description: "PR number"
    required: false
    default: ${{ github.event.number }}

outputs:
  tf_path:
    description: Terraform project path

runs:
  using: docker
  image: Dockerfile
